ITEM.ID = 8
ITEM.Name = "Key to room 304"
ITEM.Model = "models/sunabouzu/inventory_key.mdl"
ITEM.Skin = 3
ITEM.Description = "Found in room 203. I can unlock a door by using this key."
ITEM.CamPos = Vector(0, 128, 128)
ITEM.LookAtPos = Vector(0, -1, 0)
ITEM.FOV = 5
ITEM.PickupSound = "sunabouzu/keys_pickup.wav"
