ITEM.ID = 7
ITEM.Name = "Key to room 301"
ITEM.Model = "models/sunabouzu/inventory_key.mdl"
ITEM.Skin = 2
ITEM.Description = "Found in room 304. I can unlock a door by using this key."
ITEM.CamPos = Vector(0, 128, 128)
ITEM.LookAtPos = Vector(0, -1, 0)
ITEM.FOV = 5
ITEM.PickupSound = "sunabouzu/keys_pickup.wav"
